//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDiemTiepNhan
    {
        public BDiemTiepNhan()
        {
            this.BPhanHuongNhuCaus = new HashSet<BPhanHuongNhuCau>();
            this.BDieuChinhPhanHuongDistricts = new HashSet<BDieuChinhPhanHuongDistrict>();
            this.BDieuChinhPhanHuongUnits = new HashSet<BDieuChinhPhanHuongUnit>();
            this.BDieuChinhPhanHuongDistricts1 = new HashSet<BDieuChinhPhanHuongDistrict>();
            this.BDieuChinhPhanHuongUnits1 = new HashSet<BDieuChinhPhanHuongUnit>();
            this.BPhanHuongNhuCauDistricts = new HashSet<BPhanHuongNhuCauDistrict>();
            this.BPhanHuongNhuCauUnits = new HashSet<BPhanHuongNhuCauUnit>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string UnitCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public int Status { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual ICollection<BPhanHuongNhuCau> BPhanHuongNhuCaus { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongDistrict> BDieuChinhPhanHuongDistricts { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongUnit> BDieuChinhPhanHuongUnits { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongDistrict> BDieuChinhPhanHuongDistricts1 { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongUnit> BDieuChinhPhanHuongUnits1 { get; set; }
        public virtual ICollection<BPhanHuongNhuCauDistrict> BPhanHuongNhuCauDistricts { get; set; }
        public virtual ICollection<BPhanHuongNhuCauUnit> BPhanHuongNhuCauUnits { get; set; }
    }
}
