//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKeHoachXuatBanDetail
    {
        public string ThongTinBaoId { get; set; }
        public int Nam { get; set; }
        public string SoBao { get; set; }
        public int Quy { get; set; }
        public int Thang { get; set; }
        public int Ngay { get; set; }
        public int Thu { get; set; }
        public int status { get; set; }
        public Nullable<int> GiaBao { get; set; }
        public string DonSo { get; set; }
        public string Details { get; set; }
        public int Number { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string KichThuoc { get; set; }
        public string SoXuatBan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BThongTinBao BThongTinBao { get; set; }
    }
}
