//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BThongTinBao
    {
        public BThongTinBao()
        {
            this.BKyXuatBans = new HashSet<BKyXuatBan>();
            this.DMDiemIns = new HashSet<DMDiemIn>();
            this.BPhanHuongNhuCaus = new HashSet<BPhanHuongNhuCau>();
            this.BKeHoachXuatBans = new HashSet<BKeHoachXuatBan>();
            this.BKeHoachXuatBanDetails = new HashSet<BKeHoachXuatBanDetail>();
            this.BDieuChinhKHXBs = new HashSet<BDieuChinhKHXB>();
            this.BThongTinBao1 = new HashSet<BThongTinBao>();
            this.BDieuChinhPhanHuongDistricts = new HashSet<BDieuChinhPhanHuongDistrict>();
            this.BDieuChinhPhanHuongUnits = new HashSet<BDieuChinhPhanHuongUnit>();
            this.BThongTinGiaBaos = new HashSet<BThongTinGiaBao>();
            this.BPhanHuongNhuCauDistricts = new HashSet<BPhanHuongNhuCauDistrict>();
            this.BPhanHuongNhuCauUnits = new HashSet<BPhanHuongNhuCauUnit>();
        }
    
        public string Id { get; set; }
        public string MaBao { get; set; }
        public string TenBao { get; set; }
        public bool BaoTrongMucLuc { get; set; }
        public bool CoThue { get; set; }
        public double MucThue { get; set; }
        public bool BaoTrungUongDiaPhuong { get; set; }
        public string LoaiAnPham { get; set; }
        public bool BaoNgoaiVan { get; set; }
        public int SoTrang { get; set; }
        public string KichThuoc { get; set; }
        public double TrongLuong { get; set; }
        public string GiayPhep { get; set; }
        public Nullable<double> GiaVon { get; set; }
        public double GiaBia { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string MaToaSoan { get; set; }
        public string UnitCode { get; set; }
        public bool BaoCongIch { get; set; }
        public string ParentId { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<BKyXuatBan> BKyXuatBans { get; set; }
        public virtual ICollection<DMDiemIn> DMDiemIns { get; set; }
        public virtual ICollection<BPhanHuongNhuCau> BPhanHuongNhuCaus { get; set; }
        public virtual DMLoaiAnPham DMLoaiAnPham { get; set; }
        public virtual DMToaSoan DMToaSoan { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<BKeHoachXuatBan> BKeHoachXuatBans { get; set; }
        public virtual ICollection<BKeHoachXuatBanDetail> BKeHoachXuatBanDetails { get; set; }
        public virtual ICollection<BDieuChinhKHXB> BDieuChinhKHXBs { get; set; }
        public virtual ICollection<BThongTinBao> BThongTinBao1 { get; set; }
        public virtual BThongTinBao BThongTinBao2 { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongDistrict> BDieuChinhPhanHuongDistricts { get; set; }
        public virtual ICollection<BDieuChinhPhanHuongUnit> BDieuChinhPhanHuongUnits { get; set; }
        public virtual ICollection<BThongTinGiaBao> BThongTinGiaBaos { get; set; }
        public virtual ICollection<BPhanHuongNhuCauDistrict> BPhanHuongNhuCauDistricts { get; set; }
        public virtual ICollection<BPhanHuongNhuCauUnit> BPhanHuongNhuCauUnits { get; set; }
    }
}
