//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commune
    {
        public Commune()
        {
            this.Units = new HashSet<Unit>();
        }
    
        public string CommuneCode { get; set; }
        public string CommuneName { get; set; }
        public string DistrictCode { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
