//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRoutePOS
    {
        public string MailRouteCode { get; set; }
        public string FromPOSCode { get; set; }
        public string OnMailRoutePOSCode { get; set; }
        public Nullable<byte> POSOrder { get; set; }
        public string MailRouteScheduleCode { get; set; }
        public bool Type { get; set; }
        public Nullable<System.DateTime> IncomingTime { get; set; }
        public Nullable<System.DateTime> OutgoingTime { get; set; }
    
        public virtual POS POS { get; set; }
    }
}
