//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRouteSchedule
    {
        public string MailRouteScheduleCode { get; set; }
        public string MailRouteCode { get; set; }
        public string FromPOSCode { get; set; }
        public string Description { get; set; }
        public string MailRouteScheduleName { get; set; }
    
        public virtual MailRoute MailRoute { get; set; }
    }
}
