//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRoute
    {
        public MailRoute()
        {
            this.MailRouteSchedules = new HashSet<MailRouteSchedule>();
        }
    
        public string MailRouteCode { get; set; }
        public string TransportTypeCode { get; set; }
        public string MailRouteName { get; set; }
        public string Description { get; set; }
        public string MailRouteTypeCode { get; set; }
        public string FromPOSCode { get; set; }
        public Nullable<byte> MailTripFrequencePerDay { get; set; }
    
        public virtual MailRouteType MailRouteType { get; set; }
        public virtual POS POS { get; set; }
        public virtual ICollection<MailRouteSchedule> MailRouteSchedules { get; set; }
    }
}
