//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_PHBCEntities : DbContext
    {
        public DB_PHBCEntities()
            : base("name=DB_PHBCEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Commune> Communes { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DMDiemIn> DMDiemIns { get; set; }
        public virtual DbSet<DMLoaiAnPham> DMLoaiAnPhams { get; set; }
        public virtual DbSet<DMToaSoan> DMToaSoans { get; set; }
        public virtual DbSet<MailRoute> MailRoutes { get; set; }
        public virtual DbSet<MailRoutePOS> MailRoutePOS { get; set; }
        public virtual DbSet<MailRouteSchedule> MailRouteSchedules { get; set; }
        public virtual DbSet<MailRouteType> MailRouteTypes { get; set; }
        public virtual DbSet<POS> POS { get; set; }
        public virtual DbSet<POSLevel> POSLevels { get; set; }
        public virtual DbSet<POSType> POSTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SysAction> SysActions { get; set; }
        public virtual DbSet<SysDMPublic> SysDMPublics { get; set; }
        public virtual DbSet<SysDMType> SysDMTypes { get; set; }
        public virtual DbSet<SysMenu> SysMenus { get; set; }
        public virtual DbSet<SysMenuH> SysMenuHs { get; set; }
        public virtual DbSet<SysMenuV> SysMenuVs { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<TransportGroup> TransportGroups { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<BDiemTiepNhan> BDiemTiepNhans { get; set; }
        public virtual DbSet<BKyXuatBan> BKyXuatBans { get; set; }
        public virtual DbSet<BPhanHuongNhuCau> BPhanHuongNhuCaus { get; set; }
        public virtual DbSet<BThongTinBao> BThongTinBaos { get; set; }
        public virtual DbSet<BKeHoachXuatBan> BKeHoachXuatBans { get; set; }
        public virtual DbSet<BKeHoachXuatBanDetail> BKeHoachXuatBanDetails { get; set; }
        public virtual DbSet<v_Unit> v_Unit { get; set; }
        public virtual DbSet<BDieuChinhKHXB> BDieuChinhKHXBs { get; set; }
        public virtual DbSet<BDieuChinhKHXBDetail> BDieuChinhKHXBDetails { get; set; }
        public virtual DbSet<BDieuChinhPhanHuongDistrict> BDieuChinhPhanHuongDistricts { get; set; }
        public virtual DbSet<BDieuChinhPhanHuongUnit> BDieuChinhPhanHuongUnits { get; set; }
        public virtual DbSet<BThongTinGiaBao> BThongTinGiaBaos { get; set; }
        public virtual DbSet<SysDBLog> SysDBLogs { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<BPhanHuongNhuCauDistrict> BPhanHuongNhuCauDistricts { get; set; }
        public virtual DbSet<BPhanHuongNhuCauUnit> BPhanHuongNhuCauUnits { get; set; }
        public virtual DbSet<Commune_MBCSync> Commune_MBCSync { get; set; }
        public virtual DbSet<District_MBCSync> District_MBCSync { get; set; }
        public virtual DbSet<POS_MBCSync> POS_MBCSync { get; set; }
        public virtual DbSet<POSLevel_MBCSync> POSLevel_MBCSync { get; set; }
        public virtual DbSet<POSType_MBCSync> POSType_MBCSync { get; set; }
        public virtual DbSet<Province_MBCSync> Province_MBCSync { get; set; }
        public virtual DbSet<Region_MBCSync> Region_MBCSync { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit_MBCSync> Unit_MBCSync { get; set; }
        public virtual DbSet<UnitType_MBCSync> UnitType_MBCSync { get; set; }
    
        [DbFunction("DB_PHBCEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string str, string separator)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            var separatorParameter = separator != null ?
                new ObjectParameter("separator", separator) :
                new ObjectParameter("separator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[DB_PHBCEntities].[SplitString](@str, @separator)", strParameter, separatorParameter);
        }
    }
}
