//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Districts = new HashSet<District>();
            this.DMDiemIns = new HashSet<DMDiemIn>();
            this.BThongTinGiaBaos = new HashSet<BThongTinGiaBao>();
        }
    
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
        public string Description { get; set; }
        public string RegionCode { get; set; }
        public string ProvinceListCode { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<DMDiemIn> DMDiemIns { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<BThongTinGiaBao> BThongTinGiaBaos { get; set; }
    }
}
