//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDBLog
    {
        public string UserName { get; set; }
        public System.DateTime DateChange { get; set; }
        public string TableName { get; set; }
        public string RecordOld { get; set; }
        public string RecordNew { get; set; }
    }
}
