//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenuV
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ActionCode { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Pram1 { get; set; }
        public string Pram2 { get; set; }
        public string Pram3 { get; set; }
        public string QuerryString { get; set; }
        public string Url { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Description { get; set; }
        public string sys_MenuH_Id { get; set; }
    }
}
