//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHBC.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public string TransportCode { get; set; }
        public string TransportGroup { get; set; }
        public Nullable<double> TotalLoad { get; set; }
        public Nullable<byte> Status { get; set; }
        public string POSCode { get; set; }
        public string StartYear { get; set; }
        public string EndYear { get; set; }
        public Nullable<int> Partner { get; set; }
    
        public virtual POS POS { get; set; }
        public virtual TransportGroup TransportGroup1 { get; set; }
    }
}
